### PR TITLE
fix : Separate Server Routes in routes directory and Controllers in controller directory

### PR DESCRIPTION
**Pull request by Puskar-Roy**
Closes Issue #--

(If there is not already an issue for this pull request you may create one. Although optional, it is highly reccomended to create an issue prior to submitting your pull request)

### Check off the following:

- [ ] I have followed the contribution guidelines of this repository in making my contributions

### CODE REVIEW

**Comment by raspberri05** [comment]
Thanks for opening this PR! I'll review it soon.

**Comment by raspberri05** [comment]
@Puskar-Roy I took a look at your changes. It seems like there is an CORS access error when trying to use any of the routes that require the "auth" middleware. Login works fine, but the the task routes, mail routes, ai routes, etc, do not work because of the CORS error. I could not figure out the issue, so hoping you can help. I'll take a look again once you are able to make changes to fix this. Thanks.

**Review by raspberri05 — CHANGES_REQUESTED** [review]
see above for requested changes

**Comment by Puskar-Roy** [comment]
hey @raspberri05  , I've fixed the CORS issue, and now all routes, including those that require authentication, should work perfectly.

**Comment by raspberri05** [comment]
manuallly merged  due to file conflicts

**Comment by Puskar-Roy** [comment]
@raspberri05 ok no issue

**Pull request closed without merging**
