### PR TITLE
Fixed duplicate tasks bug

### PR DESCRIPTION
**Pull request by sharadChauhan7**
Closes Issue #237 

### What's being changed 

: completeTask and deleteTask function were operating on taskName (that can be duplicate).

: Changed operation being performed on taskName to taskId.

https://github.com/raspberri05/taskorial/assets/103198852/89464ef7-a10d-4cd5-bbc8-2b3f62a4689f

### CODE REVIEW

**Comment by prajjwaljaiswal** [comment]
Nice You perfectly fix this :)

**Comment by raspberri05** [comment]
Thanks for opening a PR! I'll review it soon

**Comment by sharadChauhan7** [comment]
I optimised the code, it was failing checks because i was using arrow functions inside props because of this a new function was created every time this component re-render.

its all good now.

**Review by raspberri05 — CHANGES_REQUESTED** [review]
@sharadChauhan7 there seems to be an issue with completing tasks if you complete two duplicate tasks. In this case, the task completion seems to be not propagating to the server

**Comment by raspberri05** [comment]
*i tested this by reloading the page after completing the tasks

**Review by raspberri05 — CHANGES_REQUESTED** [review]
I just took a look and found a few more issues.
If I have two of the same task and I check off both of them, the changes do not propogate to the server, as when I reload the page, both tasks appear to be unchecked. Also, if you have two duplicate tasks and one non duplicate task, and you check both the unique and duplicate task, both remain unchecked when you reload the page. You may need to look at your code regarding how completing a task is handled.

**Pull request closed without merging**
